global:
  scrape_interval:     50s
  evaluation_interval: 50s
  scrape_timeout: 50s

scrape_configs:

  - job_name: 'proposta'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['proposta:8080']